[levels]
CTRL=121
[formats]
plain = "%m%n"
standard = "%d(%d.%m.%Y %H:%M:%S) %V [%t(%M(thrd_id)):%f:%L] %m%n"
[rules]
lwmsg.=DEBUG >stdout; standard
lwmsg.=INFO >stdout; standard
lwmsg.=NOTICE >stdout; standard
lwmsg.=WARN >stdout; standard
lwmsg.=ERROR >stderr; standard
lwmsg.=FATAL >stderr; standard
lwmsg.=CTRL >stdout; standard
lwmsg.DEBUG "server_log"; standard
