[formats]
plain = "%m%n"
standard = "%d(%d.%m.%Y %H:%M:%S) %V [%t:%f:%L] %m%n"
[rules]
lwmsg.=DEBUG >stdout; standard
lwmsg.=INFO >stdout; standard
lwmsg.NOTICE >stdout; standard
lwmsg.DEBUG "server_log"; standard
